{"version":1,"ops":[{"type":3,"author":{"id":"e77d0a5f059ed8eaaa1afef6624480d02a2f025a"},"timestamp":1499193818,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDMxMjkzMzY5OQ==","github-url":"https://github.com/DFHack/dfhack/issues/1127#issuecomment-312933699"},"message":"Is this 64-bit or 32-bit DF?\nThe message looks harmless. It's really just a warning about a certain reference not being exported because exportlegends doesn't know how to export it.","files":null},{"type":3,"author":{"id":"08ba7f14908516c299e08dc022e0508fd46971bd"},"timestamp":1499253985,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDMxMzA3NjM2Mw==","github-url":"https://github.com/DFHack/dfhack/issues/1127#issuecomment-313076363"},"message":"64 bit. \n\nAlso, when running `exportlegends maps` DF crashes with the [following report](https://paste.installgentoo.com/view/8af0b0a0) from OS X and output from dfhack:\n\n    [DFHack]# exportlegends maps\n    Exporting:  Standard biome+site map map\n    [DFHack]# /Users/philip/Downloads/df_osx/dfhack: line 15: 33875 Abort trap: 6\n    DYLD_INSERT_LIBRARIES=./hack/libdfhack.dylib ./dwarfort.exe \"$@\"\n\nAnd error from stderr.log\n\n    Invoking: exportlegends maps\n    dwarfort.exe(33875,0x70000052f000) malloc: *** error for object 0x5c3e606c8: \n    incorrect checksum for freed object - object was probably modified after being freed.\n    *** set a breakpoint in malloc_error_break to debug","files":null},{"type":3,"author":{"id":"e77d0a5f059ed8eaaa1afef6624480d02a2f025a"},"timestamp":1499259452,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDMxMzA5NTExNg==","github-url":"https://github.com/DFHack/dfhack/issues/1127#issuecomment-313095116"},"message":"I think that's the same issue as #1095. I'm not sure what the original issue here is, though. What if you run \"exportlegends custom\"?","files":null},{"type":3,"author":{"id":"08ba7f14908516c299e08dc022e0508fd46971bd"},"timestamp":1499282604,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDMxMzIwMTM1NA==","github-url":"https://github.com/DFHack/dfhack/issues/1127#issuecomment-313201354"},"message":"Running `exportlegends custom` gives:\n\n    unknown reference\t48\tABSTRACT_BUILDING\n\ntimes a lot. I can't stop it and DF will probably crash at some point.","files":null},{"type":3,"author":{"id":"5221f59e75ea9db114593bbdfb180b7354aef9ed"},"timestamp":1499647860,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDMxMzk3NzEyNQ==","github-url":"https://github.com/DFHack/dfhack/issues/1127#issuecomment-313977125"},"message":"Just to make things clear, the \"unknown reference\" message should have absolutely **nothing** to do with any crashes you may be experiencing.\n\nThe following patch should get rid of that particular \"unknown reference\" message:\n```diff\ndiff --git a/exportlegends.lua b/exportlegends.lua\nindex 1072d6f..3be26f5 100644\n--- a/exportlegends.lua\n+++ b/exportlegends.lua\n@@ -418,6 +418,7 @@ function export_more_legends_xml()\n             elseif refV:getType() == df.general_ref_type.KNOWLEDGE_SCHOLAR_FLAG then -- TODO KNOWLEDGE_SCHOLAR_FLAG\n             elseif refV:getType() == df.general_ref_type.VALUE_LEVEL then -- TODO VALUE_LEVEL\n             elseif refV:getType() == df.general_ref_type.LANGUAGE then -- TODO LANGUAGE\n+            elseif refV:getType() == df.general_ref_type.ABSTRACT_BUILDING then -- TODO ABSTRACT_BUILDING\n             else\n                 print(\"unknown reference\",refV:getType(),df_enums.general_ref_type[refV:getType()])\n                 --for k,v in pairs(refV) do print(k,v) end","files":null},{"type":5,"author":{"id":"e77d0a5f059ed8eaaa1afef6624480d02a2f025a"},"timestamp":1500563782,"metadata":{"github-id":"MDEyOkxhYmVsZWRFdmVudDExNzIzMjMxNTY="},"added":["bug"],"removed":[]},{"type":4,"author":{"id":"e77d0a5f059ed8eaaa1afef6624480d02a2f025a"},"timestamp":1500563911,"metadata":{"github-id":"MDExOkNsb3NlZEV2ZW50MTE3MjMyNzQ2OQ=="},"status":2},{"type":3,"author":{"id":"e77d0a5f059ed8eaaa1afef6624480d02a2f025a"},"timestamp":1500563966,"metadata":{"github-id":"MDEyOklzc3VlQ29tbWVudDMxNjczNjg3OA==","github-url":"https://github.com/DFHack/dfhack/issues/1127#issuecomment-316736878"},"message":"I applied Quietust's patch. While that change isn't in DFHack r2, some crash fixes are, so please test with r2 and see if the crash still occurs.","files":null}]}