{"version":1,"ops":[{"type":1,"author":{"id":"df951f1236281b36dd0a5141acef1a6cd57356d5"},"timestamp":1588321682,"metadata":{"github-id":"MDU6SXNzdWU2MTA2MzU1NTY=","github-url":"https://github.com/DFHack/dfhack/issues/1562","origin":"github"},"title":"Exportlegends info fails after exporting historical figures","message":"Hi,\n\njust tried my first legends export, and ran into this crash.\nError is repeatable and occurs every time I try to run it.\n`[DFHack]# exportlegends info\n    Exporting:  World map/gen info\n    Exporting:  Legends xml\n    Exporting:  Extra legends_plus xml\n        historical figure 0/23804 (0%)\n        historical figure 10000/23804 (42%)\n        historical figure 20000/23804 (84%)\n        historical figure 23803/23804 (100%)\n...op\\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:332: Cannot read field identity.civ: not found.\nstack traceback:\n        [C]: in metamethod '__index'\n        ...op\\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:332: in global 'export_more_legends_xml'\n        ...op\\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:956: in global 'export_legends_info'\n        ...op\\Dwarf Fortress 0.47.04/hack/scripts/exportlegends.lua:1009: in local 'script_code'\n        ...pusch\\Desktop\\Dwarf Fortress 0.47.04\\hack\\lua\\dfhack.lua:680: in function 'dfhack.run_script_with_env'\n        (...tail calls...)`\nIs this me being stupid, or is it an actual error?\n\nFor debug purposes:\nOS: 10\nDFHack Version: 0.47.04-r1\n\nKind regards","files":null}]}